--use this to execute while the app starts
--DO $$
--    BEGIN
--      IF (SELECT COUNT(*) FROM store_order;) = 2 THEN
--        INSERT INTO store_order (value,date,fulfilled,customer_id,item_id)
--        VALUES
--        (40226.94*3,CURRENT_DATE,FALSE,1,4);
--      END IF;
--    END;
--    $$;

